# Generated by Django 3.2.17 on 2023-05-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=50)),
                ('max_marks', models.IntegerField()),
                ('pass_marks', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=50)),
                ('exam_id', models.IntegerField()),
                ('student_id', models.CharField(max_length=50)),
                ('marks', models.IntegerField()),
            ],
        ),
    ]
