# Generated by Django 3.2.17 on 2023-05-22 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=50)),
                ('teacher_id', models.CharField(max_length=50)),
                ('exam_id', models.IntegerField()),
                ('course_name', models.CharField(max_length=100)),
                ('section_name', models.CharField(max_length=25)),
                ('file_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
