# Generated by Django 3.2.17 on 2023-07-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='exam_name',
            field=models.CharField(default='Final', max_length=100),
            preserve_default=False,
        ),
    ]
