# Generated by Django 3.2.17 on 2023-07-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_upload_exam_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='course_id',
            field=models.CharField(default='21TS102', max_length=50),
            preserve_default=False,
        ),
    ]
