# Generated by Django 3.2.17 on 2023-03-07 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admins',
            new_name='Admin',
        ),
    ]
