# Generated by Django 3.2.17 on 2023-03-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_rename_admins_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='uni_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
