# Generated by Django 3.2.17 on 2023-03-07 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20230307_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='uni_name',
            field=models.CharField(error_messages={'unique': 'The Geeks Field you entered is not unique.'}, max_length=100, unique=True),
        ),
    ]
