# Generated by Django 3.2.17 on 2023-03-07 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_admin_uni_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='uni_name',
        ),
        migrations.AddField(
            model_name='admin',
            name='university_name',
            field=models.CharField(default='klu', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
