# Generated by Django 3.2.17 on 2023-03-07 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20230307_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admin',
            old_name='university_name',
            new_name='uni_name',
        ),
    ]
