# Generated by Django 3.2.17 on 2023-03-08 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_university_name_admin_uni_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
