# Generated by Django 3.2.17 on 2023-03-09 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_admin_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=50)),
                ('faculty_username', models.CharField(max_length=50)),
                ('section_id', models.CharField(max_length=50)),
                ('note', models.TextField(max_length=1000)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
