# Generated by Django 3.2.17 on 2023-03-09 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='faculty_username',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='section_id',
        ),
    ]
