# Generated by Django 3.2.17 on 2023-03-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='note',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
