# Generated by Django 3.2.17 on 2023-03-10 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_announcement_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='note',
            field=models.TextField(max_length=1000),
        ),
    ]
