# Generated by Django 3.2.17 on 2023-03-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_announcement_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=50)),
                ('course_id', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=20)),
            ],
        ),
    ]
