# Generated by Django 3.2.17 on 2023-03-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='faculty',
            name='teacher_id',
            field=models.CharField(max_length=50),
        ),
    ]
