# Generated by Django 3.2.17 on 2023-03-11 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20230311_1820'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
