# Generated by Django 3.2.17 on 2023-03-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_delete_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=50)),
                ('teacher_id', models.CharField(max_length=50)),
                ('teacher_name', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=50)),
                ('course_name', models.CharField(max_length=100)),
                ('section_id', models.CharField(max_length=75)),
                ('section_name', models.CharField(max_length=25)),
                ('year', models.CharField(max_length=4)),
            ],
        ),
    ]
