# Generated by Django 3.2.17 on 2023-03-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
    ]
