# Generated by Django 3.2.17 on 2023-04-01 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_classe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Classe',
        ),
    ]
