# Generated by Django 3.2.17 on 2023-04-10 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_section_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='active',
        ),
    ]
