# Generated by Django 3.2.17 on 2023-04-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_section_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
