# Generated by Django 3.2.17 on 2023-05-05 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_alter_section_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=50)),
                ('student_id', models.CharField(max_length=50)),
                ('issue', models.TextField(max_length=1000)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.TextField(default='pending')),
            ],
        ),
        migrations.AlterField(
            model_name='announcement',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
